In [1]:
url = 'https://raw.githubusercontent.com/codebasics/py/master/ML/5_one_hot_encoding/Exercise/carprices.csv'
import pandas as pd
import numpy as np
# df = pd.read_csv(url)
# df

In [7]:
# df.to_csv('carprices.csv', index=False)
df = pd.read_csv('carprices.csv')
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [8]:
dummies = pd.get_dummies(df['Car Model'])
merged = pd.concat([df, dummies], axis='columns')
# drop original col `Car Model` and dummy-col `Mercedez Benz C class`
final = merged.drop(['Car Model', 'Mercedez Benz C class'], axis='columns')
final

Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5
0     69000          18000         6        0       1
1     35000          34000         3        0       1
2     57000          26100         5        0       1
3     22500          40000         2        0       1
4     46000          31500         4        0       1
5     59000          29400         5        1       0
6     52000          32000         5        1       0
7     72000          19300         6        1       0
8     91000          12000         8        1       0
9     67000          22000         6        0       0
10    83000          20000         7        0       0
11    79000          21000         7        0       0
12    59000          33000         5        0       0

In [9]:
# Now, we know `final` dataframe covers all models.
# `BMW X5`, `Audi A5` and `Mercedez Benz C class`
# when all dummy-cols have value '0', row represents `Mercedez Benz C class`
# all are independent variables except `Sell Price($)` -> X

X = final.drop(['Sell Price($)'], axis='columns')
# dependent variable-> y
y = final['Sell Price($)']

In [11]:
# use sklearn model for Linear Regression
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model

LinearRegression()

In [13]:
#independent-> X; dependent-> y
model.fit(X, y) #independent, dependent

LinearRegression()

In [14]:
model.predict(X)

array([18705.2723644 , 35286.78445645, 24479.19112468, 41245.76426391,
       29882.98779056, 28023.6135243 , 30614.46818502, 21879.57266964,
       12182.34562104, 26183.72387884, 18929.31674102, 20409.80511857,
       30477.15426156])

In [15]:
# accuracy
model.score(X, y)

0.9417050937281083

In [16]:
# mileaga 45000, 4 yr old, Mercedez 
model.predict([[45000,4,0,0]])

array([36991.31721061])

In [17]:
#Price of BMW X5 that is 7 yr old with mileage 86000
model.predict([[86000, 7, 0,0]])

array([17818.95045785])

In [19]:
# now, we save the model into pickle file
import pickle
with open('model_pickle', 'wb') as f:
    pickle.dump(model, f)

In [20]:
# now use the model from pickle
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [22]:
# prediction using pickle-dumped model
mp.predict([[45000,4,0,0]])

array([36991.31721061])

In [23]:
# second way of saving ->`joblib`
import joblib

In [24]:
joblib.dump(model, 'model_joblib')

['model_joblib']

In [25]:
mj = joblib.load('model_joblib')

In [26]:
#Price of BMW X5 that is 7 yr old with mileage 86000
mj.predict([[86000, 7, 0,0]])

array([17818.95045785])

In [36]:
# checking different values in different methods
model.coef_

array([-3.70122094e-01, -1.33245363e+03, -2.45354074e+03, -6.73820733e+03])

In [35]:
mp.coef_

array([-3.70122094e-01, -1.33245363e+03, -2.45354074e+03, -6.73820733e+03])

In [33]:
mj.coef_

array([-3.70122094e-01, -1.33245363e+03, -2.45354074e+03, -6.73820733e+03])

In [37]:
model.intercept_

58976.625968537235

In [38]:
mp.intercept_

58976.625968537235

In [39]:
mj.intercept_

58976.625968537235